### ISSUE TITLE
Clarify relationship of getSyncTime() and timeOffset

### ISSUE THREAD

**Issue by jamesopstad** [collective-soundworks/sync#2]
I'm trying to understand how the return value of getSyncTime() and the timeOffset returned by reportFunction are related. I would expect that timeOffset + localTime would equal syncTime. I've checked this, however, and sometimes it does, sometimes it doesn't. Having looked at the source code,  I see that they are calculated in quite different ways and getSyncTime() includes stabilisation. Does this make the return of getSyncTime() more accurate? I ask because, for my use case, it would be better for the timeOffset to be set when the status changes so that I have control over when to update the offset to localTime.

**Comment by jipodine** [comment]
Since version 2.0, `getSyncTime()` does not apply directly a new `timeOffset`. It is applied gradually, to ensure stabilisation, and monotonicity. Indeed, it is _less_ accurate. 

If you want the previous behaviour, you should set `options.estimationMonotonicity` to `false` in the constructor.

But I wonder what is your use case. Do you really need `timeOffset`? Why not using `getSyncTime()` and `getLocalTime()`, for proper conversion?

**Comment by jamesopstad** [comment]
Thanks. The core of what I'm trying to do is to have visual metronomes that are synchronised across multiple devices. The reason I thought it would be better to use `timeOffset` is so that I can update this value at the start of each beat and then calculate the difference between this and the `timeOffset` value for the previous beat. This would allow me to spread any necessary adjustment over the duration of a beat. I imagined that if, instead, I was calling `getSyncTime()` on each animation frame then a change in the sync time could cause a visible jump. Perhaps I have misunderstood, though, and the way in which `getSyncTime()` updates would prevent this being an issue?

**Comment by jipodine** [comment]
Yes, `getSyncTime()` should not jump any more, so using it should solve your issue. The stabilisation spreads the adjustment of `timeOffset` over time. (Except when the synchronisation process restarts, eg. after a long network failure.)

**Comment by jamesopstad** [comment]
Great. That sounds like just what I need then.
